### ISSUE TITLE
Cannot read property 'type' of undefined?

### ISSUE THREAD

**Issue by pertrai1** [gruntjs/grunt-contrib-jshint#106]
Could someone help me understand why I am starting to get this error:

<pre><code>Warning: Cannot read property 'type' of undefined Use --force to continue.
TypeError: Cannot read property 'type' of undefined
    at Object.stmt.exps [as fud] (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:3082:19)
    at expression (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:798:29)
    at statement (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:1391:7)
    at statements (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:1444:12)
    at block (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:1566:9)
    at doFunction (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:2308:3)
    at Object.t [as nud] (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:2669:3)
    at expression (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:801:30)
    at infix.exps (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:2074:19)
    at Object.x.led (/Users/longview/Sites/immunization-web/node_modules/grunt-contrib-jshint/node_modules/jshint/src/stable/jshint.js:1114:12)</code></pre>

Thank you for any assistance in why this all the sudden started to show up.

**Comment by oleg-amdocs** [comment]
Received almost the same error. Added information on which file it occurs:

file:
C:/build/node_modules/grunt-contrib-jshint/node_modules/jshint/node_modules/htmlparser2/node_modules/domutils/lib/legacy.js

Warning: Cannot read property 'type' of undefined Use --force to continue.
TypeError: Cannot read property 'type' of undefined
    at Object.oldScope [as fud] (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:3620:38)
    at expression (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:892:32)
    at statement (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:1591:9)
    at statements (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:1634:16)
    at block (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:1753:13)
    at Object.blockstmt.labelled [as fud] (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:3961:11)
    at expression (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:892:32)
    at statement (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:1591:9)
    at statements (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:1634:16)
    at block (C:\build\node_modules\grunt-contrib-jshint\node_modules\jshint\src\jshint.js:1753:13)

package.json:
    "grunt-contrib-jshint": "~0.10.0",
